# Generated by Django 5.0.6 on 2024-05-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
