# Generated by Django 5.0.6 on 2024-05-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='length',
            field=models.CharField(default=8, max_length=20),
        ),
    ]
